apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

commonLabels:
    app: dev-kustomize
    env: dev

resources:
  - ../../base

commonAnnotations:
  note: Hello From Dev!

patches:
 - target:
      group: route.openshift.io
      version: v1
      kind: Route
   path: route-patch.yaml